config/routes.rb
Rails.application.routes.draw do
  get 'movies/show'

  get 'movie/show'

  resources :movies
  root to: redirect('/movies')
end

app/models/movie.rb
class Movie < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  def index
    @movies = Movie.all
  end

  def show
  end

  def new
    @movie = Movie.new
  end

  private
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:title, :rating, :description, :release_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title RottenPotatoes !
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tag

  %body
    = yield

app/views/movies/index.html.haml
%h1 All Movies

%table#movies
  %thead
    %tr
      %th Movie Title
      %th Rating
      %th Release Date
      %th More Info
  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title
        %td= movie.rating
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)

= link_to 'Add new movie', new_movie_path

app/views/movies/new.html.haml
%h2 Create New Movie

= form_for @movie do |f|

  = f.label :title
  = f.text_field :title

  = f.label :rating
  = f.select :rating, %w(G, PG, PG-13, R, NC-17)

  = f.label :release_date
  = f.date_select :release_date

  = f.submit 'Save Changes'

app/views/movies/show.html.haml
%h2 Details about #{@movie.title}

%ul#details
  %li
    Rating:
    = @movie.rating
  %li
    Released on:
    = @movie.release_date.strftime("%B %d, %Y")

%h3 Description:

%p#description= @movie.description

= link_to 'Back to movie list', movies_path